### ISSUE TITLE
KeyError: 'AWS_BUCKET'

### ISSUE THREAD

**Issue by presiti** [dataignitelab/athemic#4]
I found this when I was running ENTROPY and selected the AWS option in the Associations menu.
ENTROPY를 실행 중 연계 메뉴의 AWS 옵션을 선택했을 때 발견했습니다.

When the data store option is selected as 'Linked' and the linking channel is set to 'AWS Migration', the screen displays the error KeyError: 'AWS_BUCKET'.
데이터 저장소 옵션을 '연계'로 선택한 후 연계 채널을 'AWS마이그레이션'으로 했을 때 화면에 KeyError: 'AWS_BUCKET' 에러가 출력됩니다.
![ENTROPY_AWS연계](https://github.com/dataignitelab/athemic/assets/89508552/a8513e30-5019-4647-af50-e71a9d7c79be)  

Error description:
```
2024-04-12 09:52:38.800 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\datacentric\Documents\DataPlatform\athemic_github\ENTROPY\.venv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\datacentric\Documents\DataPlatform\athemic_github\ENTROPY\boot.py", line 1450, in <module>
    main()
  File "C:\Users\datacentric\Documents\DataPlatform\athemic_github\ENTROPY\boot.py", line 1350, in main
    s3_bucket_object_infos = get_aws_s3_all_infos(session["DPM_SESSION"]["AWS_BUCKET"])
KeyError: 'AWS_BUCKET'
```

We are currently working on this issue.
현재 개선 중 입니다.

**Comment by presiti** [comment]
It was confirmed that the issue was caused by requesting information about the S3 bucket without going through the if statement that checks if the length of the list is 0 when fetching the list of S3 buckets in the code. We are checking if it works properly after fixing the issue.
코드 상에서 S3 bucket의 목록을 불러 올 때 목록의 길이가 0인지 체크하는 if문을 거치지 못하고 S3 bucket에 대한 정보를 요청하여 발생하는 문제로 확인되었습니다. 현상 수정 후 정상적으로 작동하는지 확인 중에 있습니다.

**Comment by theprismdata** [comment]
해당 오류는 개선되었으며, 본 프로젝트는 다른 오픈 소스를 기반으로 다시 개발될 예정입니다.
감사합니다.
